version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=xxxyyyzzz
      - POSTGRES_DB=foodgram
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 foodgram.wsgi"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
volumes:
  static_value:
  media_value:
