# Generated by Django 3.2.14 on 2022-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipies', through='recipes.Ingredient_for_recipe', to='recipes.Ingredient', verbose_name='Список ингредиентов'),
        ),
    ]
