# Generated by Django 3.2.14 on 2022-07-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220725_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
