# Generated by Django 3.2.14 on 2022-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220812_1153'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingredient',
            name='recipes_ing_name_164c6a_idx',
        ),
    ]
