# Generated by Django 3.2.14 on 2022-08-14 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_recipes_ing_name_164c6a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
