# Generated by Django 3.2.14 on 2022-07-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.FileField(help_text='Изображение блюда', upload_to='images', verbose_name='Изображение блюда'),
        ),
    ]
