# Generated by Django 3.2.14 on 2022-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(help_text='Изображение блюда', upload_to='images', verbose_name='Изображение блюда'),
        ),
    ]
