# Generated by Django 3.2.14 on 2022-07-26 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата создания', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
