# Generated by Django 3.2.14 on 2022-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_rename_ingredient_name_ingredient_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient_for_recipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient_name'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='uniquie recipe for author'),
        ),
    ]
