# Generated by Django 3.2.14 on 2022-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, default=55, max_length=150, unique=True, verbose_name='login'),
            preserve_default=False,
        ),
    ]
